### ISSUE TITLE
Docs Update

### ISSUE THREAD

**Issue by almanac-problem** [specta-rs/tauri2#4]
Hey,

Just wanted to let you know that the README has a small issue. The instruction:

```
rspc-tauri2 = { git = "https://github.com/specta-rs/tauri2", rev = "1a41c9217ccec1814e3e4c5e343bcc9739efab40" }
```

doesn't work because the package is actually named `rspc_tauri2`. So either the README instruction should be changed or the package name. I know this is a small thing, but it confused me for a few minutes today.

Also, incredibly awesome package! This work is so helpful for people looking to develop applications that interact with local and remote back-ends.

**Comment by oscartbeaumont** [comment]
Thanks for reporting! Although this is a problem going to close as the Tauri v2 integration has been moved back into the main rspc repo. Just use the latest `rspc-tauri` release and you should be good.
